### PR TITLE
Minor spelling fixes

### PR DESCRIPTION
**Pull request by petertodd**
Everything else looks good! I'm no javascript expert, so I didn't look at your code. But your description looks good, and I agree that simply concatenating the tips is a perfectly reasonable option.

### CODE REVIEW

**Comment by zmitton** [comment]
>  I agree that simply concatenating the tips is a perfectly reasonable option
Thanks for the feedback! I was afraid I might had removed some other useful property

**Comment by petertodd** [comment]
Glad to help!

In fact, I think my original way of committing to the tips was the wrong idea: right now for most applications I think a linked list of tips is a better design, with newest (smallest) tip towards the front. That's not to say just concatenating them all is wrong - it's more efficient in some cases - just that over the spectrum of things you can use a MMR for overall a linked list is a good balance between simple and small proof size.

**Comment by zmitton** [comment]
Whether its a linked-list or not, it needs an unambiguous serialization format in which to be hashed.

Im not sure where there would be a need for the linked-list at all. Maybe because you are thinking this information needs to persist.

I found that you can get the root _functionally_ (never caching anything (roots or peaks)). Even old roots can be returned just by specifying the last leafIndex to get the historic merkle root from that point in time. It's all very cheap.

**Comment by petertodd** [comment]
The linked list is relevant in cases where you can to provide things like compact proofs of inclusion.

Basically, if I want to prove to you that the n-th most recent value in the tree is X, without a linked list I have to provide you with the digests of every tip, even if that tip refers to a tree that doesn't contain the value. With a linked list I can omit older, non-relevant, tips. This is especially relevant for recently added values.

Furthermore a linked list works efficiently with immutable copy-on-write mechanisms, as appends don't require recalculating and potentially storing every tip.

But like I say, depends on the application! In many cases those two points aren't relevant.

**Comment by petertodd** [comment]
> Whether its a linked-list or not, it needs an unambiguous serialization format in which to be hashed.

Re: unambiguous serialization, I didn't look in detail at exactly what you did. But a good way to do this is to commit to the total length of the tree at the very top. So basically the last hash operation should be something like `H(<tips> . <length>)`. The shape of a array or linked list MMR can be determined easily from the total length, as each "1" bit in the length at offset x represents the existence of a 2^x height tree in the MMR.

If you do this you *don't* need any further disambiguation of hash operations within the tree as the meaning of each is already statically determined by the length. This reduces complexity and risk by reducing the # of potentially valid-looking forms the tree could take.

**Comment by zmitton** [comment]
> The shape of a array or linked list MMR can be determined easily from the total length

[yeah totally](https://github.com/zmitton/merkle-mountain-range/blob/master/src/merkleMountainRange.js#L220) All the "static" functions I have are basically all _pure functions_. They just return array positions, given a `leafLength` and/or a `leafIndex`

For the "regular nodes" of the tree (not bag-nodes or root nodes), an array (as you proposed), is definitely the way to go 👍.  For the "database" Im using a single random access file. It is essentially just a persistent array, which I can drill _directly_ into once I calculate the indexes I need.

Saving length within the root is not something I currently do (although [flyclient](https://eprint.iacr.org/2019/226.pdf#page=16) requires something very similar (section 6.5) which I have implemented as part of its [digest function](https://github.com/zmitton/merkle-mountain-range/blob/master/src/digests.js#L6)).

But I think I have made a really innovative abstraction for proofs (that I fail to properly communicate). I see them as _sparse trees_. For Example, the picture from the readme has 34 leaves (last leaf index is 33). The `mmr.getProof([20])` function would just returns something like this:
```
{
  'nodes': {
    '38' : <hashofleaf20>,
    '39' : <hashofleaf21>,
    '40' : <hashofnode38and39>,
    '43' : <hashofnode41and42>,
    '37' : <hashofnode33and36>,
    '44' : <hashofnode40and43>,
    '45' : <hashofnode37and44>,
    '60' : <hashofnode52and59>,
    '30' : <hashofnode14and29>,
    '61' : <hashofnode45and60>,
    '62' : <hashofnode30and61>,
    '65' : <hashofnode63and64>,
  },
  'leafLength': '34'
}
```
The verifier, already knowing the merkleroot (the nature of merkle-proofs), can locally create a tree with the above data (specifically using this as its [in-memory database](https://github.com/zmitton/merkle-mountain-range/blob/master/src/db/memoryBasedDb.js)). 2 huge benefits to this. First - I can add more leaves to the proof, say leaf 23, by just adding a few more nodes to it: `{ '41' : <hashofleaf22>, '42' : <hashofleaf23> }`.

Verifying the tree is as simple as `require(mmr.getRoot()==knownRoot)`

because the rest of verifying is done on demand - calling `mmr.get(20)` traverses down from leaf 20's local peak (`nodes['62']`), checking that 
 - each touched node (and its sibling) is _present_, 
 - each set of siblings correctly hash to their parent.

After giving myself permission to explore this abstraction, I kept finding fruits:

As you may have noticed, some of the nodes in the above proof could be removed, because both of their child nodes are present, which is sufficient to recreate them. What I call an _implied node_. They are easy to find and remove from the proof using [a single loop](https://github.com/zmitton/merkle-mountain-range/blob/master/src/merkleMountainRange.js#L124). And then the `_getNodeValue` [function](https://github.com/zmitton/merkle-mountain-range/blob/master/src/merkleMountainRange.js#L153)
was refactored to be recursive - if an initial lookup fails, it returns the hash of its children instead.

But the **most** interesting thing, is that this proof tree can potentially be swapped in for the real thing. See it can do other operations, including `append()`. the key is to throw a `MissingNode` error whenever a node is "touched" that is not (recursively) present. This seems useful for a light-client to potentially run a VM on, and locally validate state transitions rather than just static data.

The _sparse tree_ abstraction works just as well on Ethereum's "patricia" tree, so I know light-clients could easily swap the state-tree for a proof-tree there.

**Comment by petertodd** [comment]
If I understand this correctly, you're doing something similar to my proofmarshal work in that proofs are things with some data pruned away.

Are you familiar with that approach?

**Comment by petertodd** [comment]
(and I should point out: proofmarshal itself is a reinvention of something a whole bunch of other people have previously independently invented)

**Comment by zmitton** [comment]
ok, yeah everything is pretty much already invented :) but now I know we're on the same page

**Pull request merged**
